In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")

数据预处理

In [5]:
df_pos=pd.read_excel("C:/Users/RAZER/Desktop/DataPreprocessing_pos.xlsx")
df_neg=pd.read_excel("C:/Users/RAZER/Desktop/DataPreprocessing_neg.xlsx")
df_pos_T=pd.concat([df_pos.iloc[:,0:1],df_pos.iloc[:,24:40]],axis=1).T
df_pos_T.columns= df_pos_T.iloc[0].values
df_pos_T=df_pos_T[1:]
df_pos_T["label"]=[1]*8+[0]*8
df_neg_T=pd.concat([df_neg.iloc[:,0:1],df_neg.iloc[:,24:40]],axis=1).T
df_neg_T.columns= df_neg_T.iloc[0].values
df_neg_T=df_neg_T[1:]
df_neg_T["label"]=[1]*8+[0]*8
x_neg=df_neg_T.iloc[:,:-1]
y_neg=df_neg_T["label"]
x_pos=df_pos_T.iloc[:,:-1]
y_pos=df_pos_T["label"]

传统分类算法（neg）

In [6]:
kf=KFold(n_splits=8,shuffle=True)
LR_acc=[]
GNB_acc=[]
SVM_acc=[]
RF_acc=[]
for train_index, test_index in kf.split(x_neg):
    print(train_index,test_index)
    x_neg_train=x_neg.iloc[list(train_index)]
    x_neg_test=x_neg.iloc[list(test_index)]
    y_neg_train=y_neg.iloc[list(train_index)]
    y_neg_test=y_neg.iloc[list(test_index)]
#   LR
    logistic_model = LogisticRegression(solver="liblinear").fit(x_neg_train, y_neg_train)
    logistic_y_pred = logistic_model.predict(x_neg_test)
    logistic_acc=accuracy_score(logistic_y_pred, y_neg_test)
    print("Logistic_Regression：",logistic_acc)
    LR_acc.append(logistic_acc)
# 贝叶斯
    gaussian_model = GaussianNB().fit(x_neg_train, y_neg_train)
    gaussian_y_pred = gaussian_model.predict(x_neg_test)
    gaussian_acc=accuracy_score(gaussian_y_pred, y_neg_test)
    print("Gaussian Navie Bayes: ",gaussian_acc)
    GNB_acc.append(gaussian_acc)
# 支持向量机
    svc_model = SVC(kernel="linear").fit(x_neg_train, y_neg_train)
    svc_y_pred = svc_model.predict(x_neg_test)
    support_vector_acc=accuracy_score(svc_y_pred, y_neg_test)
    print("Support Vector Classifier: ",support_vector_acc)
    SVM_acc.append(support_vector_acc)
# Random Forest
    randomForest_model = RandomForestClassifier(n_estimators=12).fit(x_neg_train, y_neg_train)
    randomForest_y_pred = randomForest_model.predict(x_neg_test)
    random_forest_acc=accuracy_score(randomForest_y_pred, y_neg_test)
    print("Random Forest Classifier: ",random_forest_acc)
    RF_acc.append(random_forest_acc)
print("The mean accuracy of Logistic_Regression (negative):",np.mean(LR_acc))
print("The mean accuracy of Gaussian Navie Bayes (negative):",np.mean(GNB_acc))
print("The mean accuracy of Support Vector Classifier (negative):",np.mean(SVM_acc))
print("The mean accuracy of Random Forest Classifier (negative):",np.mean(RF_acc))

[ 0  1  2  3  5  6  7  8  9 10 11 13 14 15] [ 4 12]
Logistic_Regression： 1.0
Gaussian Navie Bayes:  0.5
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
[ 0  1  2  3  4  6  7  8  9 11 12 13 14 15] [ 5 10]
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
[ 0  1  2  3  4  5  6  8  9 10 12 13 14 15] [ 7 11]
Logistic_Regression： 0.5
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  0.5
Random Forest Classifier:  0.5
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 15] [13 14]
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
[ 0  1  4  5  6  7  8  9 10 11 12 13 14 15] [2 3]
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
[ 0  1  2  3  4  5  7  8 10 11 12 13 14 15] [6 9]
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
[ 

维度权重-neg

In [7]:
import heapq
logistic_model = LogisticRegression(solver="liblinear").fit(x_neg, y_neg)
importance =list(logistic_model.coef_[0])
max_num_index_list = map(importance.index, heapq.nlargest(10, importance))
min_num_index_list = map(importance.index, heapq.nsmallest(10,importance))
print("预测类别1的重要性top10特征索引:",list(max_num_index_list),"\n预测类别0的重要性top10特征索引",list(min_num_index_list))


预测类别1的重要性top10特征索引: [330, 449, 122, 809, 867, 870, 893, 906, 900, 305] 
预测类别0的重要性top10特征索引 [897, 357, 123, 131, 360, 428, 874, 383, 797, 276]


In [18]:
df_neg1=df_neg.loc[[330, 449, 122, 809, 867, 870, 893, 906, 900, 305]]
outputpath='C:/Users/RAZER/Desktop/DataPreprocessing_neg1.csv'
df_neg1.to_csv(outputpath,sep=',',index=False,header=False)

传统分类算法（pos）

In [133]:
kf=KFold(n_splits=8,shuffle=True)
LR_acc=[]
GNB_acc=[]
SVM_acc=[]
RF_acc=[]
for train_index, test_index in kf.split(x_pos):
#     print(train_index,test_index)
    x_pos_train=x_pos.iloc[list(train_index)]
    x_pos_test=x_pos.iloc[list(test_index)]
    y_pos_train=y_pos.iloc[list(train_index)]
    y_pos_test=y_pos.iloc[list(test_index)]
#     LR
    logistic_model = LogisticRegression(solver="liblinear").fit(x_pos_train, y_pos_train)
    logistic_y_pred = logistic_model.predict(x_pos_test)
    logistic_acc=accuracy_score(logistic_y_pred, y_pos_test)
    print("Logistic_Regression：",logistic_acc)
    LR_acc.append(logistic_acc)
# 贝叶斯
    gaussian_model = GaussianNB().fit(x_pos_train, y_pos_train)
    gaussian_y_pred = gaussian_model.predict(x_pos_test)
    gaussian_acc=accuracy_score(logistic_y_pred, y_pos_test)
    print("Gaussian Navie Bayes: ",gaussian_acc)
    GNB_acc.append(gaussian_acc)
# 支持向量机
    svc_model = SVC(kernel="linear").fit(x_pos_train, y_pos_train)
    svc_y_pred = svc_model.predict(x_pos_test)
    support_vector_acc=accuracy_score(svc_y_pred, y_pos_test)
    print("Support Vector Classifier: ",support_vector_acc)
    SVM_acc.append(support_vector_acc)
# Random Forest
    randomForest_model = RandomForestClassifier(n_estimators=10).fit(x_pos_train, y_pos_train)
    randomForest_y_pred = randomForest_model.predict(x_pos_test)
    random_forest_acc=accuracy_score(randomForest_y_pred, y_pos_test)
    print("Random Forest Classifier: ",random_forest_acc)
    RF_acc.append(random_forest_acc)
print("The mean accuracy of Logistic_Regression (positive):",np.mean(LR_acc))
print("The mean accuracy of Gaussian Navie Bayes (positive):",np.mean(GNB_acc))
print("The mean accuracy of Support Vector Classifier (negative):",np.mean(SVM_acc))
print("The mean accuracy of Random Forest Classifier (negative):",np.mean(RF_acc))

Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
Logistic_Regression： 0.5
Gaussian Navie Bayes:  0.5
Support Vector Classifier:  0.5
Random Forest Classifier:  0.5
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  0.5
Logistic_Regression： 1.0
Gaussian Navie Bayes:  1.0
Support Vector Classifier:  1.0
Random Forest Classifier:  1.0
The mean accuracy of Logistic_Regression (positive): 0.9375
The mean accuracy of

维度权重(pos)

In [135]:
import heapq
logistic_model = LogisticRegression(solver="liblinear").fit(x_pos, y_pos)
importance =list(logistic_model.coef_[0])
max_num_index_list = map(importance.index, heapq.nlargest(10, importance))
min_num_index_list = map(importance.index, heapq.nsmallest(10,importance))
print("预测类别1的重要性top10特征索引:",list(max_num_index_list),"\n预测类别0的重要性top10特征索引",list(min_num_index_list))

预测类别1的重要性top10特征索引: [1588, 1438, 2244, 264, 406, 2225, 1440, 2122, 647, 642] 
预测类别0的重要性top10特征索引 [643, 458, 363, 366, 592, 2232, 1803, 1110, 639, 1068]


In [20]:
df_pos1=df_pos.loc[[1588, 1438, 2244, 264, 406, 2225, 1440, 2122, 647, 642]]
outputpath='C:/Users/RAZER/Desktop/DataPreprocessing_pos1.csv'
df_pos1.to_csv(outputpath,sep=',',index=False,header=False)